project:
  type: website

website:
  title: "FAIRqual"
  site-url: https://fairqual.org
  page-navigation: true
  search: false
  announcement:
    dismissable: true
    content: "**News!** Our abstract has been accepted for [STS NL 2026](blog/posts/2026-02-05-sts-nl2026/). We'll present in the track 'How to Make Science Better'. [Read more â†’](blog/posts/2026-02-05-sts-nl2026/)"
    type: warning
    icon: megaphone
  page-footer: 
    left: | 
        This project was supported by the 
        [Open Research Data Program of the ETH Board](https://ethrat.ch/en/eth-domain/open-research-data/)
    right:
      - text: About
        href: about.qmd
      - icon: "envelope-at"
        href: "mailto:franziska.mohr@usys.ethz.ch?subject=FAIRqual request"
        aria-label: Email
      - icon: github
        href: https://github.com/fairqual
        aria-label: GitHub
  navbar:
    background: "#18A5C5" 
    title: false
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: blog/
      - text: "Slides"
        href: gallery/slides/
      - text: "Proposal"
        href: gallery/proposal/
      - text: "Events"
        href: events/
      - text: "Support"
        menu:
          - text: "Email us"
            icon: "envelope-at"
            href: "mailto:franziska.mohr@usys.ethz.ch?subject=FAIRqual request"
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/fairqual/website/issues"

format:
  html:
    theme:
      light: [litera, style/theme.scss]
    highlight-style: a11y-dark
    css: style/styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    mainfont: "Atkinson Hyperlegible"
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    include-in-header: 
        - text: |
            <script defer data-domain="fairqual.org" src="https://plausible.io/js/script.file-downloads.js"></script>

execute:
  freeze: auto


